### ISSUE TITLE
您好，这些绑定的信息，看您并没有实现，这些方法的实现是可以解决什么呢？

### ISSUE THREAD

**Issue by kc991229** [wangwenx190/qtlottie#4]
connect(m_drawEngine, &QtLottieDrawEngine::durationChanged, this, &QtLottieWidget::durationChanged);
    connect(m_drawEngine, &QtLottieDrawEngine::sizeChanged, this, &QtLottieWidget::sourceSizeChanged);
    connect(m_drawEngine, &QtLottieDrawEngine::loopsChanged, this, &QtLottieWidget::loopsChanged);
    connect(m_drawEngine, &QtLottieDrawEngine::devicePixelRatioChanged, this, &QtLottieWidget::devicePixelRatioChanged);

比如&QtLottieWidget::sourceSizeChanged，是可以适配资源大小改变吗

**Comment by wangwenx190** [comment]
怎么没有实现？

**Comment by wangwenx190** [comment]
> 是可以适配资源大小改变吗

lottie动画有画布尺寸，不同的lottie文件有不同的尺寸，这个信号是干这个的

**Comment by kc991229** [comment]
> > 是可以适合配资来源大改小改吗
> 
> lottie动画有画布尺寸，不同的lottie文件有不同的尺寸，这个信号是干这个的

got thank you~
